@startuml
left to right direction
actor "Admin" as fc
rectangle CarSell {
  usecase "Content Management" as UC1
  usecase "Pay for Food" as UC2
  usecase "Drink" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml